test:
    cmd: "node"
    name: "test"
    args:
        - "--expose-gc"
        - "--max-old-space-size=1800"
        - "./test/thin-perf.js"
    sh: true
    env:
        NODE_ENV: "development"
    atomCommandName: "atom-custom:npmtest"
