kind: pipeline
name: release

platform:
  arch: arm

steps:
- name: test
  image: rust
  commands:
  - rustup component list --installed
  - apt-get update
  - apt-get install -y musl-tools musl-dev
  - cargo install cargo-make --debug
  - cargo make zip-release-ci-flow --env CARGO_MAKE_RELEASE_FLOW_TARGET=arm-unknown-linux-gnueabihf
  - ls -lsa
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release
    files: ./*.zip
  when:
    event: tag

