kind: pipeline
name: release

platform:
  arch: arm

steps:
- name: test
  image: rust
  commands:
  - apt-get install -y musl-tools
  - cargo install cargo-make
  - cargo make zip-release-ci-flow --env CARGO_MAKE_RELEASE_FLOW_TARGET=arm-unknown-linux-musl
  - tree
  - ls -lsa
