name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish Binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cp ./README.md ./test123.zip
    - name: check build
      run: |
        ls -l
    - name: Upload Binaries
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.zip'
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
