name: Temp Tests
on: [push]
jobs:
  ci:
    name: Continuous Integration
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: step1
      run: echo token len chrlen(${GITHUB_TOKEN})
