name: Temp Tests
on: [push]

jobs:
  temp:
    name: Temp
    runs-on: ubuntu-latest
    steps:
    - name: check token
      run: |
        echo echo token len expr length "${{ secrets.GITHUB_TOKEN }}"
